# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "egoist-aws"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = false
s3_prefix = "egoist-aws"
region = "us-east-2"
profile = "gchamb"
image_repositories = ["MonthlyCronFunction=563672049341.dkr.ecr.us-east-2.amazonaws.com/egoist-monthly-cron", "WeeklyCronFunction=563672049341.dkr.ecr.us-east-2.amazonaws.com/egoist-weekly-cron", "SqsFfmpegFunction=563672049341.dkr.ecr.us-east-2.amazonaws.com/egoist-sqs-ffmpeg"]

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
